const imgData = [
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733094/arafat/acrylic/10_opf_oyshc3.jpg",
    title: "Rickshaw and Reflection ",
    medium: "Acrylic on Canvas",
    size: "152 cm x 122 cm ",
    tag: "",
  },
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733094/arafat/acrylic/Baul-min_a7ques_1_prm7rr.jpg",
    title: "Baul",
    medium: "Acrylic on Canvas",
    size: "52 cm x 61 cm",
    tag: "",
  },
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733094/arafat/acrylic/Beauty_in_Balck_pnsnj0.jpg",
    title: "The Silent God",
    medium: "Acrylic on Canvas",
    size: "76 cm x 76 cm",
    tag: "",
  },
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733095/arafat/acrylic/Childhood_Days_qqqpfv.jpg",
    title: "Two children plucking waterlilies from a pond",
    medium: "Acrylic on Canvas",
    size: "60 cm x 60 cm ",
    tag: "",
  },
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733096/arafat/acrylic/Dadu_hwcfja.jpg",
    title: "Sadhu Baba ",
    medium: "Acrylic on Canvas",
    size: "76 cm x 76 cm",
    tag: "",
  },
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733095/arafat/acrylic/DualityofMind-min_ncc1on_1_rrepnt.jpg",
    title: "Reflection",
    medium: "Acrylic on Canvas",
    size: "152 x 122 cm",
    tag: "",
  },
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733094/arafat/acrylic/Innocence_e2cxp1.jpg",
    title: "Innocence",
    medium: "Acrylic on Canvas",
    size: "76 cm x 76 cm",
    tag: "",
  },
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733095/arafat/acrylic/MysticMusician-min_vxffkz_1_pnmgcc.jpg",
    title: "The Music of Mid Night Blue",
    medium: "Acrylic on Canvas",
    size: "76 cm x 76 cm",
    tag: "",
  },
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733095/arafat/acrylic/Old_Man_with_Teacup_ooj5tw.jpg",
    title: "An Old Man with a Coup of Tea on Morning Light",
    medium: "Acrylic on Canvas",
    size: "",
    tag: "",
  },
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733095/arafat/acrylic/Palga_jsq8ms.jpg",
    title: "Palga and Red Uniform",
    medium: "Acrylic on Canvas",
    size: "76 cm x 91 cm",
    tag: "",
  },
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733095/arafat/acrylic/Shadhu_r74ulr.jpg",
    title: "Sadhu",
    medium: "Acrylic on Canvas",
    size: "",
    tag: "",
  },
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733096/arafat/acrylic/Subconscious_Mind_yaqj7y.jpg",
    title: "Old Face II",
    medium: "Acrylic on Canvas",
    size: "76 cm x 76 cm",
    tag: "",
  },
  {
    category: "Acrylic",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773733097/arafat/acrylic/Two_Faces_jhjmwd.jpg",
    title: "Two Baul Faces",
    medium: "Acrylic on Canvas",
    size: "76 cm x 76 cm",
    tag: "",
  },
  {
    category: "Sketch",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779171406/arafat/sketch/Fish_Market_w56qge.jpg",
    title: "A Local Fish Market",
    medium: "Pencil Sketch",
    size: "29 cm x 21 cm ",
    tag: "",
  },
  {
    category: "Sketch",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779171407/arafat/sketch/Happy_Face_tqxeyh.jpg",
    title: "The Smiling Face",
    medium: "Pen & Ink om paper",
    size: "21cm x 29 cm ",
    tag: "",
  },
  {
    category: "Sketch",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779171406/arafat/sketch/IL_Pradhan_tjh1go.jpg",
    title: "Portrait of I.L.Pradhan at Darjeeling ",
    medium: "Pencil Sketch",
    size: "21cm x 29 cm",
    tag: "",
  },
  {
    category: "Sketch",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779171407/arafat/sketch/Nepali_Boy_zq7e6f.jpg",
    title: "A Nepali Gurkha at Darjeeling Rail Station ",
    medium: "Pen & Ink on Paper",
    size: "56 cm x 76 cm ",
    tag: "",
  },
  {
    category: "Sketch",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779171408/arafat/sketch/Nepali_Man_g58spo.jpg",
    title: "A Nepali face wearing a traditional Dhaka Topi",
    medium: "Pen & Ink on Paper",
    size: "21cm x 29 cm",
    tag: "",
  },
  {
    category: "Sketch",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779171408/arafat/sketch/Nepali_Porter_yjawhz.jpg",
    title: "A smiling Nepali porter",
    medium: "Dry Point",
    size: "21cm x 29 cm",
    tag: "",
  },
  {
    category: "Sketch",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779171408/arafat/sketch/Old_Man_gambuj.jpg",
    title: "A winter Morning",
    medium: "pen & Ink",
    size: "56 cm x 76 cm",
    tag: "",
  },
  {
    category: "Sketch",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779171408/arafat/sketch/Serenity_aacyjg.jpg",
    title: "Face",
    medium: "Cross hatching in Pen",
    size: "21cm x 29 cm",
    tag: "",
  },
  {
    category: "Sketch",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779171410/arafat/sketch/Struggle_yilvml.jpg",
    title: "Struggle",
    medium: "Pen & Ink",
    size: "76 cm x 56 cm",
    tag: "",
  },
  {
    category: "Sketch",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172033/arafat/sketch/Picture1_mbnltw.jpg",
    title: "A Tanti",
    medium: "colour pencil on paper",
    size: "56 cm x 60 cm",
    tag: "",
  },
  {
    category: "Sketch",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172159/arafat/sketch/Picture4_idcodc.jpg",
    title: "A Burmese lady with a Pipe",
    medium: "Colpur pencil on Paper",
    size: "56 cm x 60 cm",
    tag: "",
  },
  {
    category: "Sketch",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172033/arafat/sketch/Picture2_c5miyl.jpg",
    title: "A tribe Lady",
    medium: "Colour pencil",
    size: "46 cm x 45cm ",
    tag: "",
  },
  {
    category: "Digital",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172369/arafat/digital/Alone_birqw2.jpg",
    title: "The Lonely Symphony on Another Planet",
    medium: "Digital artwork",
    size: "",
    tag: "",
  },
  {
    category: "Digital",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172370/arafat/digital/An_old_story_nas59v.jpg",
    title: "An Old Story and Fantasy",
    medium: "Digital artwork",
    size: "",
    tag: "",
  },
  {
    category: "Digital",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172371/arafat/digital/IMG_0046_xqee1v.jpg",
    title: "Rolando",
    medium: "Digital artwork",
    size: "",
    tag: "",
  },
  {
    category: "Digital",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172372/arafat/digital/IMG_0048_qn19v5.jpg",
    title: "Neymar Jr",
    medium: "Digital artwork",
    size: "",
    tag: "",
  },
  {
    category: "Digital",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172373/arafat/digital/IMG_0050_xaqvna.jpg",
    title: "Leonel Messi",
    medium: "Digital artwork",
    size: "",
    tag: "",
  },
  {
    category: "Digital",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172374/arafat/digital/Materialistic_evolution_ts4s6m.jpg",
    title: "Material study- shiny Effect ",
    medium: "Digital artwork",
    size: "",
    tag: "",
  },
  {
    category: "Digital",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172374/arafat/digital/Mindful_Meditation_orq0dr.jpg",
    title: "Meditation into abandoned architecture",
    medium: "Digital artwork",
    size: "",
    tag: "",
  },
  {
    category: "Digital",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172375/arafat/digital/Objective_Reality_omzx2a.jpg",
    title: "Metamorphosis",
    medium: "Digital artwork",
    size: "",
    tag: "",
  },
  {
    category: "Digital",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172377/arafat/digital/Red_in_Green_emddai.jpg",
    title: "A Bunch of Red Flowers",
    medium: "Digital artwork",
    size: "",
    tag: "",
  },
  {
    category: "Digital",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172378/arafat/digital/Textures_of_Reality_lignqi.jpg",
    title: "The Runner",
    medium: "Photoshop CS6 and drawing tablet",
    size: "",
    tag: "",
  },
  {
    category: "Digital",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172378/arafat/digital/Runner_gfi7az.jpg",
    title: "The Runner",
    medium: "Photoshop CS6 and drawing tablet",
    size: "",
    tag: "",
  },
  {
    category: "Digital",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779172380/arafat/digital/The_Beauty_of_Sundarbans_o8tth3.jpg",
    title: "The Forest and River ",
    medium: "Digital artwork",
    size: "",
    tag: "",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736729/arafat/water-color/_DSC5088_1_n9lrpo.jpg",
    title: "Flower Vase",
    medium: "watercolour on paper",
    size: "40.64 × 40.64 cm",
    tag: "Sold Out",
    price: "$420",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736730/arafat/water-color/03_oph_a1fgug.jpg",
    title: "A Heritage Building I",
    medium: "Watercolour on Paper",
    size: "21 × 29.7 cm",
    tag: "In Stock",
    price: "$420",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736731/arafat/water-color/04_opg_on5ep8.jpg",
    title: "A Heritage Building II",
    medium: "Watercolour on Paper",
    size: "21 × 29.7 cm",
    tag: "In Stock",
    price: "$420",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736731/arafat/water-color/11_opx_qvgson.jpg",
    title: "Sampan",
    medium: "Watercolour on Paper",
    size: "38 × 56 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736732/arafat/water-color/12_opg_kg1sal.jpg",
    title: "Fishery Ghat at Coxes Bazar ",
    medium: "Watercolour on Paper",
    size: "56 × 76 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736737/arafat/water-color/344831971_1039257337041671_6668475810998282838_n_1_e6q81i.jpg",
    title: "Old Dhaka Street View  ",
    medium: "Watercolour on Paper",
    size: "76 x 56 cm",
    tag: "Sold Out",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736734/arafat/water-color/346073092_6545135178853857_1457228547336631173_n_1_bocfan.jpg",
    title: "Old Dhaka Street View",
    medium: "Watercolour on Paper",
    size: "76 x 56 cm",
    tag: "Sold Out",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736736/arafat/water-color/An_Evening_of_Mysterious_Sky_fa2vnd.jpg",
    title: "Sunset over a fishermans hut",
    medium: "Watercolour on Paper",
    size: "38 x 56 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736736/arafat/water-color/IMG_5151_1_aciyci.jpg",
    title: "Baul Song ",
    medium: "Watercolour on Paper",
    size: "38 x 26 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736738/arafat/water-color/IMG_5155_1_1_njz372.jpg",
    title: "Harmonious colour of Rickshaws ",
    medium: "Watercolour on Paper",
    size: "26 x 30 cm",
    tag: "Sold OUt",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736739/arafat/water-color/IMG_5167_1_a4zhdh.jpg",
    title: "Rickshaws from Birds Eye View ",
    medium: "Watercolour on Paper",
    size: "76 x 56 cm",
    tag: "Sold Out",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736741/arafat/water-color/Metro_Railway_constraction_site_kbnybq.jpg",
    title: "First light over Dia-Bari, Uttara",
    medium: "Watercolour on Paper",
    size: "29.7 x 21 cm",
    tag: "Not For Sale",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736742/arafat/water-color/Painting_post_2f_ruayhv.jpg",
    title: "A Morning at Old Dhaka ",
    medium: "Watercolour on Paper",
    size: "21 x 29.7 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736744/arafat/water-color/Painting_post_3g_ckpgzd.jpg",
    title: "Subtitle colours of Dhaka",
    medium: "Watercolour on Paper",
    size: "76 x 56 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736745/arafat/water-color/Painting_post_9f_xd0jg1.jpg",
    title: "The Morning light of Dhaka",
    medium: "Watercolour on Paper",
    size: "76 x 56 cm",
    tag: "Sold Out",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736746/arafat/water-color/Painting_post_18g_kolgrc.jpg",
    title: "Baul Son II",
    medium: "Watercolour on Paper",
    size: "26 x 30 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736748/arafat/water-color/Rickshaw_Garge_gar5o7.jpg",
    title: "Rickshaw Garage in Morning",
    medium: "Watercolour on Paper",
    size: "26 x 30 cm",
    tag: "Sold Out",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736749/arafat/water-color/Still_Life_hu2zy4.jpg",
    title: "Still-life study I",
    medium: "Watercolour on Paper",
    size: "26 x 30 cm",
    tag: "Not For Sale",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736750/arafat/water-color/Vinatage_Appeal_b0jzbg.jpg",
    title: "Still-life study I",
    medium: "Watercolour on Paper",
    size: "30× 26 cm",
    tag: "Not For Sale",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736752/arafat/water-color/Water_Lily_Pond_cum6pm.jpg",
    title: "Waterlily in the pond at My Village I",
    medium: "Watercolour on Paper",
    size: "29.7 x 21 cm",
    tag: "Sold Out",
  },

  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736753/arafat/water-color/Water_Lily_futl7b.jpg",
    title: "Waterlily in the pond at My Village I",
    medium: "Watercolour on Paper",
    size: "28 x 38 cm",
    tag: "Sold Out",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736755/arafat/water-color/WhatsApp_Image_2023-05-17_at_11.28.39_AM_ixrdll.jpg",
    title: "Mist and Reflections",
    medium: "Watercolour on Paper",
    size: "76 x 56 cm",
    tag: "Sold Out",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736756/arafat/water-color/WhatsApp_Image_2023-05-22_at_1.14.00_PM_1_hypumw.jpg",
    title: "Flower-Vase III",
    medium: "Watercolour on Paper",
    size: "38x 56 cm",
    tag: "",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736759/arafat/water-color/WhatsApp_Image_2023-06-02_at_11.50.35_AM_tzqdy5.jpg",
    title: "A View of Chawk Bazaar Mosque at Old Dhaka I",
    medium: "Watercolour on Paper",
    size: "76 x 56 cm",
    tag: "",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736760/arafat/water-color/WhatsApp_Image_2023-06-02_at_11.50.37_AM_ywfpid.jpg",
    title: "A View of Chawk Bazaar Mosque at Old Dhaka II",
    medium: "Watercolour on Paper",
    size: "76 x 56 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1773736761/arafat/water-color/WhatsApp_Image_2023-06-20_at_6.59.10_PM_rqgicd.jpg",
    title: "Rickshaws from Birds Eye View II",
    medium: "Watercolour on Paper",
    size: "56 x 76 cm",
    tag: "Sold Out",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779174265/arafat/water-color/2_do7q0f.jpg",
    title: "Sydney Harbor View ",
    medium: "Watercolour on Paper",
    size: "28 x 38 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779174256/arafat/water-color/1_a46zxr.jpg",
    title: "Harbour Bridge view through the waterbus station",
    medium: "Watercolour on Paper",
    size: "28 x 38 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779174258/arafat/water-color/3_yvwr9j.jpg",
    title: "Yellow waterbus at Sydney Harbour",
    medium: "Watercolour on Paper",
    size: "38 x 56 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779174258/arafat/water-color/4_ozxq95.jpg",
    title: "Plein air at Circular Quay, Sydney",
    medium: "Watercolour on Paper",
    size: "38 x 56 cm",
    tag: "Sold Out",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779174442/arafat/water-color/487520627_1579874919621663_7823711366951465551_n_zch5vh.jpg",
    title: "Boats at Gold Cost Beach",
    medium: "Watercolour on Paper",
    size: "38 x 56 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779174442/arafat/water-color/487807464_1578644059744749_789309711311813005_n_kfxhox.jpg",
    title: "Boats at Gold Cost Beach",
    medium: "Watercolour on Paper",
    size: "56 x 76 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779174443/arafat/water-color/488251545_1581527166123105_4941455108881461434_n_ksg6td.jpg",
    title: "Seagulls over Gold Coast beaches",
    medium: "Watercolour on Paper",
    size: "56 x 38 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779174690/arafat/water-color/488960760_1585300342412454_8799603618456194448_n_vv82ed.jpg",
    title: "Vibrant Town Hall before Victorian buildings",
    medium: "Watercolour on Paper",
    size: "38 x 56 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779174691/arafat/water-color/503807021_1631876627754825_7032714581322018222_n_j7hi2u.jpg",
    title: "Cycling over the Harbour Bridge",
    medium: "Watercolour on Paper",
    size: "56 x 38 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779174787/arafat/water-color/5_ywpgfp.jpg",
    title: "Morning at Gold Coast",
    medium: "Watercolour on Paper",
    size: "56 x 38 cm",
    tag: "Sold Out",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779174831/arafat/water-color/sddsd_pswxpw.jpg",
    title: "Mind, Memory and Reflections ",
    medium: "Watercolour on Paper",
    size: "28 x 38 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779175013/arafat/water-color/Picture2scfsfc_wkeqoj.jpg",
    title: "Echoes of Urban Life ",
    medium: "Watercolour on Paper",
    size: "28 x 38 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779175014/arafat/water-color/Picture3fdfdfgvgvd_xzy9tr.jpg",
    title: "Memories of Blue Mountains ",
    medium: "Watercolour on Paper",
    size: "28 x 38 cm",
    tag: "In Stock",
  },
  {
    category: "Water Color",
    url: "https://res.cloudinary.com/softenin/image/upload/v1779175015/arafat/water-color/Picture4dvdvd_ra8izs.jpg",
    title: "Beside the River George at Blue mountains ",
    medium: "Watercolour on Paper",
    size: "28 x 38 cm",
    tag: "In Stock",
  },
];

export default imgData;
