export const blogdata = [
  {
    id: 1,
    img: "https://res.cloudinary.com/softenin/image/upload/v1772308246/arafat/Image3_ealxyg.png",
    title: "Serentity of Blue Beach",
    des: "Watercolor on Paper",
    size: "16x 22 inches",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/softenin/image/upload/v1772308246/arafat/Image2_zyemwy.png",
    title: "Serentity of Blue Beach",
    des: "Watercolor on Paper",
    size: "16x 22 inches",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/softenin/image/upload/v1772308246/arafat/Image1_age6gn.png",
    title: "Serentity of Blue Beach",
    des: "Watercolor on Paper",
    size: "16x 22 inches",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/softenin/image/upload/v1772308246/arafat/Image3_ealxyg.png",
    title: "Serentity of Blue Beach",
    des: "Watercolor on Paper",
    size: "16x 22 inches",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/softenin/image/upload/v1772308246/arafat/Image2_zyemwy.png",
    title: "Serentity of Blue Beach",
    des: "Watercolor on Paper",
    size: "16x 22 inches",
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/softenin/image/upload/v1772308246/arafat/Image1_age6gn.png",
    title: "Serentity of Blue Beach",
    des: "Watercolor on Paper",
    size: "16x 22 inches",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/softenin/image/upload/v1772308246/arafat/Image3_ealxyg.png",
    title: "Serentity of Blue Beach",
    des: "Watercolor on Paper",
    size: "16x 22 inches",
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/softenin/image/upload/v1772308246/arafat/Image2_zyemwy.png",
    title: "Serentity of Blue Beach",
    des: "Watercolor on Paper",
    size: "16x 22 inches",
  },
  {
    id: 9,
    img: "https://res.cloudinary.com/softenin/image/upload/v1772308246/arafat/Image1_age6gn.png",
    title: "Serentity of Blue Beach",
    des: "Watercolor on Paper",
    size: "16x 22 inches",
  },
];
